services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant@sha256:a81e875974c909957da5407a85d42409581a1f3c1ae202642519430389baf1ad"
    volumes:
      - ./hass-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
  mosquitto:
    image: eclipse-mosquitto:2.0.21@sha256:94f5a3d7deafa59fa3440d227ddad558f59d293c612138de841eec61bfa4d353
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/data/:/mosquitto/data/